Fred/autocannon
oslabs-beta/Swell-v13 pull request #9
Opened 2023-03-23 06:32 UTC by Fredkim21

LoadTest.ts is basic function for load testing, response data is the total send, total received, total missed, and the average response times that was received. The added some input locations but requires styling and better functionality. At the moment the URL needs to get linked to the original url location and need to connect the response to an actual chart. 
was not able to get any testing libraries to work in a node/typescript/electron setting. Artillery and k6 both require some command line functionality to work correctly and autocannon relies on node.js core modules which are also not available as an electron app. would have had to go about setting up another api endpoint in the serverside and runs the autocannon tests but that is still not certain to work so I just wrote a basic test.

2023-03-23 17:59 UTC, csuzukida approved these changes
LGTM, let us know if the # of requests getting sent off bug gets addressed

2023-03-23 18:18 UTC, nattiechan requested changes
Could we also put in a check to ensure only HTTP/2 requests (for now?) can show up in `ScheduleContainer.jsx`?

Also, I think we may want to rename the container file since this is no longer about scheduling requests

2023-03-23 18:18 UTC, nattiechan commented on src/client/components/legacy-components/LoadTest.ts
> +    }
What kind of error are we anticipating here? If it is error on Swell's end, should we count this as `missed` as well?

2023-03-23 21:49 UTC, Fredkim21 commented
in the bug fixes i fix the total number of requests getting sent and not being sent is getting recorded and returned. changed the name of the ScheduleContainer.jsx to TestContainer.tsx

2023-03-24 00:05 UTC, nattiechan reviewed
Looking good so far!

2023-03-24 00:05 UTC, nattiechan commented on src/client/components/legacy-components/LoadTest.ts
> +    }
A few questions regarding this approach. I don't have the answer for any of these but curious what your thoughts are.

1. What does `totalNotSent` metric tell us? From the way this is setup it feels like it is accounting for the amount of time that Swell needs to set up and send the request, correct? Is this more of a reflection of the performance of Swell vs. the endpoint?

2. It looks like we are awaiting the request to be done before initiating the next one. What if the time it takes to send the request is longer than the request per second? Could we possibly utilize `setInterval` here, even with concurrent users?

2023-03-24 00:05 UTC, nattiechan commented on src/client/components/legacy-components/TestContainer.tsx
> +    </div>
Bump on my earlier comment regarding restricting the results to only HTTP/2 requests. I am wondering if this is incorporated somewhere?

2023-03-24 06:30 UTC, Fredkim21 commented on src/client/components/legacy-components/LoadTest.ts
> + */
Wasnt sure on what we wanted to return yet so at the moment its fluid. but could add some more.

2023-03-25 17:08 UTC, Fredkim21 commented on src/client/components/legacy-components/LoadTest.ts
> +    }
TotalNotSent, the way im thinking about it is the amount that the endpoint is not allowing in. So this is the case in terms of in production api endpoints.
Actually after some more testing it seems that this is still the case even on severs that I am working on in dev. I had gotten some limits even then. But this really seems to depend on the website and how they are monitoring and allowing refresh rates. Some websites only allow < 5 per calls per second where others are allowing the max, which seems to be about 70-80 per second.

2023-03-25 20:29 UTC, nattiechan reviewed
One last question before approval

2023-03-25 20:29 UTC, nattiechan commented on src/client/components/legacy-components/LoadTest.ts
> +  // concurrentUsers: number, at this time concurrentUsers is not
Let's remove this as well

2023-03-25 20:29 UTC, nattiechan commented on src/client/components/legacy-components/LoadTest.ts
> +      let requestsThisSecond = 0;
Let's define typing here

2023-03-25 20:29 UTC, nattiechan commented on src/client/components/legacy-components/TestContainer.tsx
> +            }}
Looks like right now we are just logging the results in console logs. Have we thought about the plan on how to display the results in the UI? It is fine if we have not gotten that far yet, though I just want to check in where your thought process is at

2023-03-25 21:49 UTC, Fredkim21 commented on src/client/components/legacy-components/LoadTest.ts
> +  // concurrentUsers: number, at this time concurrentUsers is not
ok removed

2023-03-25 21:49 UTC, Fredkim21 commented on src/client/components/legacy-components/LoadTest.ts
> +      let requestsThisSecond = 0;
defined all the types i could find

2023-03-25 21:50 UTC, Fredkim21 commented on src/client/components/legacy-components/TestContainer.tsx
> +            }}
I was planning on sending the results in console.log into the response body but just havent been able to get to it at the moment. Am open to ideas on to where and how data should be displayed.

2023-03-25 23:17 UTC, nattiechan approved these changes
Looks great! This is contingent on the consensus that the UI will be done in a separate PR :)

2023-03-25 23:17 UTC, merged